server:
  port: 8888


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:derby:D://DerbyDB;create=true;
#    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
#    druid:
#      initial-size: 5
#      max-active: 10
#      min-idle: 5
#      # 配置获取连接等待超时的时间
#      max-wait: 50000
#      validation-query: select 1 from sysibm.sysdummy1
#      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      #配置一个连接在池中最小生存的时间，单位是毫秒
#      ##### 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒 #####
#      min-evictable-idle-time-millis: 300000
#      #打开PSCache，并且指定每个连接上PSCache的大小
#      pool-prepared-statements: false
#      ##### 当连接空闲时，是否执行连接测试. #######
#      test-while-idle: true
#      ###### 当从连接池借用连接时，是否测试该连接. ####
#      test-on-borrow: false
#      ####### 在连接归还到连接池时是否测试该连接 #######
#      test-on-return: false
#      #######  配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙   #######
#      #####   监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall #######
#      filters:
#      commons-log.connection-logger-name: stat,wall,log4j
